language: go

sudo: false

env:
  global:
    # SLACK_TOKEN
    - secure: "SKA9st/AvlorcIkL5IRgxjZpVipxI4qHBhbIPXXJ8JRtCzKhvq2CNXqQA5l/sqCRC91R44hZTrQkHrC8PMu/MAxPS5FtNQzO7/xUYcuYiv6C+4d4H+urZqhipBJHKWbf9tZl1noVguIDPsyp/Tt00tCxd1gjpHXuC4zHM98TUhXFJ0dTOa2r7WyQfTk7O6ITfRCZFeR2IUCJRlehMUz0XqIMkMNIXBpEVrQlzsJLf04WSG9uY44nq6QBGed0oyNVAq9Qvv6rcOXmwI0emDIIt6v79tuyz/quQfacH0kuxj/w99a4s0KOyyaz2All4Dh+dEkRCe0tgs8VSaufer6ZEcfL9rNjwdpPmWxt/buLtfGx533LJqFZYV4QiMm+VGsxeGp79v7WrFnNqks9JBOFGOnWVKm781nSGlF/Ek19hbZVUAOaBPyWPs+rqtjz9Uw2Iziry3UB/rfBhZnI15pwTDHdemcIFZm6FGwvAj+fzxKojG+TVJwM3hy2Lpf8K5QeV1Q3eN/jYEsrThUjPyqrGJW/3yKmSESsfDsQKFarFVmSK9jm1w4KDMWQ8zA9I/H1iEkuHEZ4vkPxLUCO28t2etqMknzMugJFcRB5xagYP5MX/0EbLt54ra1qpx2T4BxYw26bUNlr4zKsLuv0LY35Oe0XnyQ7tCO25Ds7ZjR6DUY="

go:
  - 1.6
  - 1.7

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
before_script:
  - go vet
script:
  - go build ./...
  - go test -v

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
