language: go

sudo: false

go:
  - 1.6
  - 1.7

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
before_script:
  - go vet
script:
  - go build ./...
  - go test -v

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
